stages:
  - security
  - renovate

include:
  - project: 'valentin178/renovate-ci'
    file: '.gitlab/renovate-scan.yml'

check_generated_files:
  stage: .pre
  image: alpine:latest
  script:
    - apk add --no-cache bash diffutils
    - bash scripts/generate.sh --check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
